name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt install -y gcc g++ clang lld make patchelf python3-dev ccache python3 python3-pip
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install noneprompt toml Nuitka text2art art
        
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --standalone --lto=yes --assume-yes-for-downloads\
          --clang --include-package=core --include-package=menu --include-package=utils \
          --include-data-dir=bash=bash --show-progress\
          --include-data-file=config.toml=config.toml \
          --output-dir=dist --output-filename=gpu_tool --remove-output main.py
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/gpu_tool
        
    - name: Create Release & upload artifact
      uses: softprops/action-gh-release@v1
      with:
        files: dist/gpu_tool
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
